SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

ASTEROID_MIN_SPIN = 10
ASTEROID_MAX_SPIN = 60

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5
SHOT_LIFETIME = 1.5

ASTEROID_POINTS = {
    1: 100,
    2: 50,
    3: 20,
}

EXPLOSION_DURATION = 0.45

ASTEROID_SPAWN_MODE = "waves"
LEVEL_START_ASTEROIDS = 3
LEVEL_ASTEROIDS_INCREMENT = 1
LEVEL_SPEED_INCREASE = 0.08
LEVEL_INTERMISSION = 1.25
