SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_COOLDOWN = 0.3  # seconds
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5
SHOT_LIFETIME = 1.5  # seconds

# Scoring values per asteroid kind (1=small, 3=large)
ASTEROID_POINTS = {
    1: 100,  # small
    2: 50,   # medium
    3: 20,   # large
}

# Visual effects
EXPLOSION_DURATION = 0.45  # seconds
